---
# 配置各地址与格式
txt:
      path: ./txt/      # 导出的聊天记录放在txt目录下
      name: 『联盟群』花落闪暖，国服安一.txt
excel:
      path: ./          # 生成的excel文件放在当前目录
      name: 落花-统计打卡.xlsx
      sheet: 8.26-9.1

forbiddenWords:         # 配置过滤词
      - 格式
      - Q群管家

necessaryWords:         # 配置必须词
      - 打卡