---
# 配置各地址与格式
txt:
      path: ./txt/      # 导出的聊天记录放在txt目录下
      name: 『联盟群』花落闪暖，国服安一.txt
excel:
      path: ./          # 生成的excel文件放在当前目录
      name: 落花机密表_糙汉子版.xlsx
      #      name: test.xlsx
      sheet: 9.9-9.15

forbiddenWords:         # 配置过滤词
      - 格式
      - Q群管家
      - 林落

necessaryWords:         # 配置必须词
      - 落花
      - 打
      - 次